### ISSUE TITLE
Build packages on Ubuntu 22.04 (Jammy, latest LTS)

### ISSUE THREAD

**Issue by l0b0** [linz/linz-software-repository#119]
See #118 - might have to wait for either of the upstreams to resolve their issues.

**Comment by l0b0** [comment]
Might've been fixed by https://github.com/linz/linz-software-repository/pull/131, but package_cloud has no changelog, and the [code diff](https://my.diffend.io/gems/package_cloud/0.3.08/0.3.11) isn't clear enough to tell.

**Comment by billgeo** [comment]
Cool. Thanks. Closing.
