### ISSUE TITLE
Provide github action to build packages

### ISSUE THREAD

**Issue by strk** [linz/linz-software-repository#19]
See instructions in https://help.github.com/en/actions/building-actions/creating-a-docker-container-action

The idea is that other repositories would be able to, in one of their workflows, include a snippet like:
> uses: linz/linz-software-repository@v1

And pass it arguments to build packages for their environment.

@imincik I don't see the option to put this under the https://github.com/linz/ds-group-epics/issues/104 epic, is this repository not part of the appropriate ZenHub boards ?

**Comment by imincik** [comment]
Repo is public now.

**Comment by strk** [comment]
Thanks. This issue still needs to be kept open until we do provide a working github action (it's being worked on in branch https://github.com/linz/linz-software-repository/tree/github-action
