### ISSUE TITLE
GH action: push build Debian tag to git once package is built for 'test' repo

### ISSUE THREAD

**Issue by imincik** [linz/linz-software-repository#29]
Once package is built for 'test' repo (new release tag), Debian bulild tag `ex.: debian/1.8.0-1linz_trusty1` has to be pushed back to git repo.

**Comment by strk** [comment]
Also the debian/changelog needs be pushed back to repo. I'm not sure if by default a github-action has permission to do so.

**Comment by strk** [comment]
The docker image creates a temporary branch to work with, and does its things there.
It is left to the caller to merge the temporary branch back, push the changes upstream if needed, remove the temporary branch.

Pushing the changes upstream could be implemented in the docker image itself, if made optional (and we'd need secrets to obtain authorization to push). If we do that, the pushing should be optional.

Right now the Docker entry point accepts a PUBLISH_TO_REPOSITORY environment variable, which can be set to `dev` or `test`. I'm not sure it is "safe" or recommendable to use the _same_ environment variable to also determine whether we want the debian/changelog and tag pushed back to the repository. Or we could support PUSH_PACKAGING_CHANGES_BACK_TO_REPOSITORY environment variable... The container will need to know to _which_ branch to push the changes, as it's not necessarely known in advance. Also which remote !

**Comment by strk** [comment]
I've added support for pushing tag to configurable remote in #30  - please review. Users of the action will still need to specify where to push (and provide credentials) - I have this in staging with postgresql-dbpatc, see https://github.com/linz/postgresql-dbpatch/actions/runs/122323131
