### ISSUE TITLE
Drop 'debian_revision' from package version - use native Debian package format

### ISSUE THREAD

**Issue by imincik** [linz/linz-software-repository#32]
`debian_revision` is optional - https://www.debian.org/doc/debian-policy/ch-controlfields.html#version .Drop 'debian_revision' from package version and use native Debian package format. Most probably this requires change of Debian format to `native in `debian/source/format` to `3.0 (native)` for each packaged software.

**Comment by strk** [comment]
Shall the Docker image include or exclude the `debian_revision`
field based on conent of `debian/source/format` ?

When going "native", do we still need the `linz~${distro}1` suffix ?
(I never understood the final 1 after distro, btw)

**Comment by imincik** [comment]
> Shall the Docker image include or exclude the `debian_revision` field based on conent of `debian/source/format` ?

Yes, packaging process should check `format` and according it should include or don't include Debian revision. But check `dch` before implementing something by yourself. It might be able to set Debian revision automatically. 

>When going "native", do we still need the `linz~${distro}1` suffix ? (I never understood the final 1 after distro, btw)

Yes, we need `distro` value to be able to have the same version of software packaged for multiple Ubuntu versions. Number behind distro is really redundant.

**Comment by strk** [comment]
Ok, redundant number after distro I removed in https://github.com/linz/linz-software-repository/pull/33

As for debian revision, I'd just never append one. Since we're always building from a git repository there would never be a need to build 2 different packages for the _same_ commit/tag, no matter the effects of debian/format, right ? I took this path in the PR above as well, please review

**Comment by imincik** [comment]
OK, I agree with that

**Comment by strk** [comment]
Ok I did drop the debian revision as of v4 tag
