### ISSUE TITLE
Lost Debian tags during automated packaging

### ISSUE THREAD

**Issue by imincik** [linz/linz-software-repository#40]
We are loosing Debian tags (ex.: `debian/1.0.0-1linz_trusty1`) during automated Debian packaging process.

Current know list of packages without Debian release tag is :

* linz-bde-schema
* linz-bde-uploader
* linz-lds-bde-schema
* linz-bde-schema
* linz-lds-bde-private

**Comment by strk** [comment]
I don't see missing debian tags. Details follow

# linz-bde-schema

The action which automatically built the package for 1.11.0 (latest release) is here:
https://github.com/linz/linz-bde-schema/runs/868937720?check_suite_focus=true#step:5:242

According to logs it succeeded at pushing the tag and indeed it is found [here](https://github.com/linz/linz-bde-schema/releases/tag/debian%2F1.11.0-linz_bionic)

That action failed instead to push changes back to master branch, but I did that manually with
https://github.com/linz/linz-bde-schema/commit/a235d2cc77d5394cfc83087ab6db4de15713bb50

# linz-bde-uploader

The action which automatically built the package for 2.10.0 (latest release) is here:
https://github.com/linz/linz-bde-uploader/runs/894386938?check_suite_focus=true#step:5:433

It succeeded at pushing the tag, which can be found [here](https://github.com/linz/linz-bde-uploader/releases/tag/debian%2F2.10.0-linz_bionic)

That action failed instead to push changes back to master branch, which I did manually with
https://github.com/linz/linz-bde-uploader/commit/fab84ae33ff5b814d649b81fb1bfd322681b0381

# linz-lds-bde-schema

The action which built the package for 1.11.1 (latest release) is here:
https://github.com/linz/linz-lds-bde-schema/runs/892857329?check_suite_focus=true#step:5:342

It succeeded at pushing the tag, which can be found [here](https://github.com/linz/linz-lds-bde-schema/releases/tag/debian%2F1.11.1-linz_bionic)

That action also succeeded at [pushing changes](https://github.com/linz/linz-lds-bde-schema/commit/c183177f70e510e61580e0880ed4eb850ca3cd1f) back to stable branch (stable branch is not protected)

# linz-lds-bde-private

The action which built the package for 1.3.0 (latest release) is here:
https://github.com/linz/linz-lds-bde-private/runs/868911052?check_suite_focus=true#step:5:235

It succeeded at pushing the tag, which can be found [here](https://github.com/linz/linz-lds-bde-private/releases/tag/debian%2F1.3.0-linz_bionic)

That action failed instead to push changes back to master branch, which I did manually with
https://github.com/linz/linz-lds-bde-private/commit/a6c00be29a19b541bba507baf70572c689857b5d (master)
https://github.com/linz/linz-lds-bde-private/commit/44de4b7a32caa7c3c11daa4880fd903bae88ea04 (1.3 branch)
