### ISSUE TITLE
Temporary '<version-start> tag appears in repository

### ISSUE THREAD

**Issue by imincik** [linz/linz-software-repository#41]
Temporary '<version-start> tag used for automated packaging appears in repository. For example `1.12-start` in `linz-bde-schema` package

**Comment by strk** [comment]
What appears in packagecloud depends on what environemnt variables are passed to this docker container or which parameters are passed to this github action. In particular, the packages are uploaded when PACKAGECLOUD_REPOSITORY is set. Callers should take care of deciding when to set or not set that variable/parameter, there's no knowledge in this action/dockerimage about the meaning of tags.
