### ISSUE TITLE
Remove reference to PostgreSQL repo?

### ISSUE THREAD

**Issue by l0b0** [linz/linz-software-repository#70]
I can't tell why the PostgreSQL repo is included in the Dockerfile. Unless it's actually needed for building we should remove it.

**Comment by palmerj** [comment]
It's needed for building many bde processor packages including postgresql-dbpatch and postgresql-tableversion

**Comment by l0b0** [comment]
This repo shouldn't need to know about the dependencies of "child" repos, but it would of course be a fair bit of work to pull it out.
